version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - rtd
        - social-cards

sphinx:
  builder: html
  fail_on_warning: true
  configuration: docs/conf.py
